### ISSUE TITLE
libze_loader.so is missing

### ISSUE THREAD

**Issue by AntonTimofeev** [oneapi-src/level-zero#32] opened 2020-07-30 13:23 UTC
Hi,

Could you please put the libze_loader.so symlink in the .deb package also?
Currently there are only files with versions installed, e.g. libze_loader.so.0.91

Thank you.
BR,
Anton

**Comment by jandres742** [comment] 2020-08-08 18:22
`libze_loader.so` is in the devel package, following standard practices, see here https://www.debian.org/doc/debian-policy/ch-sharedlibs.html

**Comment by rwmcguir** [comment] 2021-03-15 15:08
Can we close this bug out? This is Debian standard practice and not a bug...

**Closed** 2021-03-30 13:28 UTC
